import table from "./conferences.json";
import { conferenceKey, gameConferenceKeys } from "./follows";
import { isFixture } from "./model";
import type { Game } from "./model";

/**
 * Every college conference the hub can name, keyed by league path.
 *
 * Generated by scripts/harvest-conferences.mjs and committed. ESPN names a
 * conference only on games where both sides share one, so the generator
 * sweeps a season rather than reading a day: college football's opening
 * Saturdays are almost entirely cross-conference and would name nothing.
 *
 * THE IDS ARE LEAGUE-SCOPED and the collision is not hypothetical. In the
 * generated file the ACC is 1 in college football and 2 in college
 * basketball, and the Summit League is 49 for the men and 47 for the
 * women. Nothing here takes a bare id.
 *
 * COLLEGE ONLY, and that is the data's decision. Measured 2026-09-06:
 * ESPN's scoreboard carries no conference or division on any NFL, NBA, MLB
 * or NHL competitor. The standings endpoint does, which is a different
 * request and a feature nobody has asked for yet.
 */

export interface Conference {
  /** `${leagueKey}:${conferenceId}`, the follow key. */
  key: string;
  /** ESPN's short form: "SEC", "Big Ten", "Mountain West". */
  label: string;
  /** Its formal name: "Southeastern Conference". */
  name: string;
}

const TABLE = table as Record<
  string,
  Record<string, { name: string; shortName: string }>
>;

/** Does this league have conferences at all? */
export function hasConferences(leagueKey: string): boolean {
  return leagueKey in TABLE;
}

/** One conference by its follow key, or nothing if we cannot name it. */
export function byKey(key: string): Conference | undefined {
  const cut = key.indexOf(":");
  if (cut <= 0) return undefined;
  const row = TABLE[key.slice(0, cut)]?.[key.slice(cut + 1)];
  return row
    ? { key, label: row.shortName, name: row.name }
    : undefined;
}

/**
 * The conferences present in a set of games, named and sorted.
 *
 * Off the LOADED games rather than the whole table, exactly as the sidebar's
 * Teams list already works: a Tuesday in November has four conferences
 * playing and offering all thirteen would be a list of mostly dead chips.
 *
 * AN ID WE CANNOT NAME IS DROPPED, deliberately. Those are real — the
 * college football board carries FCS opponents whose own conferences the
 * FBS sweep never names — and a chip reading "Conference 179" is worse
 * than no chip: it filters to something the person cannot recognise and
 * did not ask for.
 */
export function conferencesIn(games: readonly Game[]): Conference[] {
  const keys = new Set<string>();
  for (const g of games) for (const k of gameConferenceKeys(g)) keys.add(k);
  return [...keys]
    .map(byKey)
    .filter((c): c is Conference => c !== undefined)
    .sort((a, b) => a.label.localeCompare(b.label));
}

/**
 * The conferences a single fixture belongs to, for a card to draw.
 *
 * One on a conference game, two on a cross-conference one, none on
 * anything professional.
 */
export function conferencesOf(game: Game): Conference[] {
  if (!isFixture(game)) return [];
  return [
    conferenceKey(game.leagueKey, game.home),
    conferenceKey(game.leagueKey, game.away),
  ]
    .filter((k): k is string => k !== null)
    .map(byKey)
    .filter((c): c is Conference => c !== undefined);
}

/**
 * The Power 4, as follow keys, plus the independents.
 *
 * FIVE ENTRIES for a thing called four, and the fifth is the point: Notre
 * Dame is an FBS independent (id 18), so a Power 4 preset without it drops
 * the one independent anybody wants. That id is also the one the harvest
 * script cannot learn on its own, for the same reason — an independent
 * never plays a conference game, so ESPN never names its group. See EXTRA
 * in scripts/harvest-conferences.mjs.
 *
 * College football only. Basketball's power conferences are a different
 * argument with a different answer (the Big East plays no football at
 * all), and guessing one here would be inventing a category.
 */
export const POWER_FOUR: readonly string[] = [
  "football/college-football:1", // ACC
  "football/college-football:4", // Big 12
  "football/college-football:5", // Big Ten
  "football/college-football:8", // SEC
  "football/college-football:18", // FBS Independents, i.e. Notre Dame
];
