import catalog from "./leagues.json";

/**
 * Every sport and league the hub can offer (plan 010 phase 5).
 *
 * Generated by scripts/harvest-leagues.mjs and committed, so browsing never
 * waits on a network call. Every row was confirmed by ESPN itself before it
 * reached the file: the generator probes each candidate's scoreboard, and a
 * 200 proves the slug is real because an out-of-season league answers 200
 * with no events. The names and the marks are the ones ESPN gave back, not
 * ones typed here and hoped for.
 *
 * The limit is worth saying plainly: this is what our SCHEDULE SOURCE
 * covers, which is not every sport that exists. Darts, snooker and netball
 * are not missing because nobody thought of them; they are missing because
 * nothing here can tell you when they are on.
 */

export interface CatalogLeague {
  /** `sport/slug`, exactly as the endpoint wants it: "soccer/eng.1". The id
   * everything else keys on, and the thing that is fetched. */
  path: string;
  /** What a person calls it: "Premier League", "NFL", "Six Nations". */
  label: string;
  /** Its formal name: "English Premier League". */
  name: string;
  logo?: string;
}

export interface CatalogSport {
  /** ESPN's own path segment: "soccer", "mma". */
  key: string;
  /** What a person calls it: "Soccer", "Fighting". */
  name: string;
  /** Biggest sports first; leagues alphabetical inside. */
  leagues: CatalogLeague[];
}

export const SPORTS: CatalogSport[] = catalog.sports;

/** Every league, flat. */
export const ALL_LEAGUES: CatalogLeague[] = SPORTS.flatMap((s) => s.leagues);

const BY_PATH = new Map(ALL_LEAGUES.map((l) => [l.path, l]));

/** One league by its path, or undefined for a path we no longer carry —
 * which is what a saved follow looks like after a regeneration drops it. */
export function league(path: string): CatalogLeague | undefined {
  return BY_PATH.get(path);
}

/** The sport a league belongs to. */
export function sportOf(path: string): CatalogSport | undefined {
  return SPORTS.find((s) => s.leagues.some((l) => l.path === path));
}

/**
 * Sports whose NAME matches, for the picker's first step.
 *
 * Matched on the sport's name only, not on its leagues: step one asks
 * "which sport", and a search for "cup" turning up Soccer, Rugby and
 * Cricket because each has a cup in it answers a question nobody asked.
 */
export function searchSports(query: string): CatalogSport[] {
  const q = query.trim().toLowerCase();
  if (!q) return SPORTS;
  return SPORTS.filter((s) => s.name.toLowerCase().includes(q));
}

/**
 * Leagues matching, within one sport or across all of them.
 *
 * Both names are searched, because they diverge more than you would
 * think: you look for "Premier League" where the formal name is "English
 * Premier League". The path is in there too, since that is where a code
 * like "eng.1" actually lives.
 */
export function searchLeagues(
  query: string,
  sport?: CatalogSport,
): CatalogLeague[] {
  const pool = sport ? sport.leagues : ALL_LEAGUES;
  const q = query.trim().toLowerCase();
  if (!q) return pool;
  return pool.filter(
    (l) =>
      l.label.toLowerCase().includes(q) ||
      l.name.toLowerCase().includes(q) ||
      l.path.toLowerCase().includes(q),
  );
}
