import catalog from "./leagues.json";

/**
 * Every sport and league the hub can offer (plan 010 phase 5).
 *
 * Generated by scripts/harvest-leagues.mjs and committed, so browsing never
 * waits on a network call. Every row was confirmed by ESPN itself before it
 * reached the file: the generator probes each candidate's scoreboard, and a
 * 200 proves the slug is real because an out-of-season league answers 200
 * with no events. The names and the marks are the ones ESPN gave back, not
 * ones typed here and hoped for.
 *
 * The limit is worth saying plainly: this is what our SCHEDULE SOURCE
 * covers, which is not every sport that exists. Darts, snooker and netball
 * are not missing because nobody thought of them; they are missing because
 * nothing here can tell you when they are on.
 */

export interface CatalogLeague {
  /** `sport/slug`, exactly as the endpoint wants it: "soccer/eng.1". The id
   * everything else keys on, and the thing that is fetched. */
  path: string;
  /** What a person calls it: "Premier League", "NFL", "Six Nations". */
  label: string;
  /** Its formal name: "English Premier League". */
  name: string;
  logo?: string;
}

export interface CatalogSport {
  /** ESPN's own path segment: "soccer", "mma". */
  key: string;
  /** What a person calls it: "Soccer", "Fighting". */
  name: string;
  /** Biggest sports first; leagues alphabetical inside. */
  leagues: CatalogLeague[];
}

/**
 * What WE call a sport, where that differs from what the generator got.
 *
 * Adam's, and it is one entry: soccer is FUTBOL here. Small, and not
 * nothing — the catalog is generated from an American source and takes
 * its wording, and this app is not obliged to. It is the one sport whose
 * name is a regional choice rather than a fact.
 *
 * DISPLAY ONLY. `key` stays "soccer" everywhere it matters: it is the
 * catalog path's first segment, the fetch URL, and half of every stored
 * league id. Renaming that would be a migration for a word.
 *
 * Both words stay searchable. See ALIASES.
 */
const SPORT_NAMES: Record<string, string> = {
  soccer: "Fútbol",
};

/**
 * Extra words a sport can be found by.
 *
 * "futbol" without the accent, because nobody reaching for a search box
 * types one, and "soccer" because renaming the label must not take away
 * the word most of this app's users would actually reach for.
 */
const ALIASES: Record<string, string> = {
  soccer: "soccer futbol futbol",
};

export const SPORTS: CatalogSport[] = catalog.sports.map((s) => ({
  ...s,
  name: SPORT_NAMES[s.key] ?? s.name,
}));

/** Every league, flat. */
export const ALL_LEAGUES: CatalogLeague[] = SPORTS.flatMap((s) => s.leagues);

const BY_PATH = new Map(ALL_LEAGUES.map((l) => [l.path, l]));

/**
 * Every word a league can be found by, lowercased, keyed by path.
 *
 * Built once. It includes the league's own two names and its path, AND
 * ITS SPORT'S, which is the half that makes searching feel like it works:
 * "hockey" is a thing a person types expecting every hockey league, and
 * nothing in a league's own row says which sport it belongs to. Both the
 * sport's key and its display name go in, because they diverge ("hockey"
 * against "Ice Hockey", "mma" against "Fighting", "soccer" against
 * "Fútbol"), plus any ALIASES, which is how the accent-free spelling and
 * the word we stopped displaying both keep working.
 */
const HAYSTACK = new Map<string, string>(
  SPORTS.flatMap((s) =>
    s.leagues.map((l) => [
      l.path,
      `${l.label} ${l.name} ${l.path} ${s.key} ${s.name} ${ALIASES[s.key] ?? ""}`.toLowerCase(),
    ]),
  ),
);

/** One league by its path, or undefined for a path we no longer carry —
 * which is what a saved follow looks like after a regeneration drops it. */
export function league(path: string): CatalogLeague | undefined {
  return BY_PATH.get(path);
}

/** The sport a league belongs to. */
export function sportOf(path: string): CatalogSport | undefined {
  return SPORTS.find((s) => s.leagues.some((l) => l.path === path));
}

/**
 * Sports whose NAME matches, for the picker's first step.
 *
 * Matched on the sport's name only, not on its leagues: step one asks
 * "which sport", and a search for "cup" turning up Soccer, Rugby and
 * Cricket because each has a cup in it answers a question nobody asked.
 */
export function searchSports(query: string): CatalogSport[] {
  const q = query.trim().toLowerCase();
  if (!q) return SPORTS;
  return SPORTS.filter((s) => s.name.toLowerCase().includes(q));
}

/**
 * Leagues matching, within one sport or across all of them.
 *
 * Both names are searched, because they diverge more than you would
 * think: you look for "Premier League" where the formal name is "English
 * Premier League". The path is in there too, since that is where a code
 * like "eng.1" actually lives. And the SPORT, so that typing "hockey"
 * finds every hockey league rather than the none that have the word in
 * their name. See HAYSTACK.
 *
 * Every term has to match, so "german soccer" narrows rather than widens.
 * Terms rather than the raw string because the fields are concatenated:
 * "soccer eng.1" is a sensible thing to type and matches nothing as one
 * substring.
 */
export function searchLeagues(
  query: string,
  sport?: CatalogSport,
): CatalogLeague[] {
  const pool = sport ? sport.leagues : ALL_LEAGUES;
  const terms = query.trim().toLowerCase().split(/\s+/).filter(Boolean);
  if (terms.length === 0) return pool;
  return pool.filter((l) => {
    const hay = HAYSTACK.get(l.path) ?? "";
    return terms.every((t) => hay.includes(t));
  });
}
